### ISSUE TITLE
Clone Phase 2 repository and make a list of bugs.

### ISSUE THREAD

**Issue by chloehumphrey** [cs-450-project/se-phase2#1]
- [ ] Clone our Phase 2 handoff.
- [ ] Submit a screenshot of console output after running the test file.
- [ ] Make a list of 5-10 bugs that you see in the repository and post it here as a comment. These can include issues that obviously impact execution, inconsistencies, or just random stuff that doesn't look quite right.  

*I've updated the README with steps to execute the program. This ONLY works using Windows Command Prompt (not PowerShell, bash, or any variation of Linux/Mac). If you're on Mac, you can't run it right now. Just look through the code to find bugs.*

**Comment by chloehumphrey** [comment]
#### Bugs
- Run file does not work for Linux/Mac
- Jest configuration doesn't allow test files to compile and run separately (i.e. tests have to be in the /src directory to work) 
- 'Output.ts' is overcomplicated as console.log is the same as std::out 
- Cannot use relative paths when passing a URL file
- There is no consistent rounding for latency and score values
- Latency values seem to be measured in milliseconds (should be seconds to two decimal points)

**Comment by YaminiKrubha** [comment]
1. In URLParser.ts, the error handling logs an error message but does not throw or return the error.
2. Some of the tests lack proper setup or teardown, which leads to inconsistent results.
3. The current test suite lacks coverage for edge cases, such as invalid URLs or network errors, which could lead to undetected bugs.
4. In Responsivemaintainers.ts, the logic for calculating date differences could be consolidated to reduce redundancy.
5. Jest coverage are not met because test suite lacks sufficient tests to execute all statements, branches, lines, and functions.

**Comment by WillKissel02** [comment]
Output

![image](https://github.com/user-attachments/assets/107ce9fd-28f4-41fa-9cc5-71616d35bde1)

Bugs
1. testingRepo folder is never deleted after clone
2. rampScore calculation seems just checks for a bunch of readme headings in a very inefficient stack of if statements
3. RepoClone contains ramp score calculation, perhaps the class should be renamed or split
4. cloneRepository has no logging on successful runs
5. analyzeReadme has no logging or error handling

**Comment by jtwellsp** [comment]
![Screenshot 2024-10-15 213148](https://github.com/user-attachments/assets/5dd9c0a4-00d0-49f0-8359-75f41ad24ebd)

Note: 

It now runs if you try it in Powershell

Bugs:

1. Does not run in WSL and also does not support Linux running because of the node out format
2. License metric is does not work properly and displays 0 even if it has the license
3. Netscore has rounding issues that would cause it to fail autograder
4. The jest, test files don't have full line coverage 
5. Autograder does not even run for this program

**Comment by adhabib** [comment]
- As mentioned previously I'm unable to run the program on Mac, so possible bugs:
- In RepoClone.ts, global variables can lead to unexpected behavior especially in an asynchronous context
- In VerifyURL.ts, the regex for extracting the package name might fail if the URL format changes slightly
- In BusFactor.ts, the while (true) loop could potentially run indefinitely if there is an issue with pagination or the API response.
- In the same file, the ONE_YEAR_AGO constant is calculated once and reused, which might not be accurate if the function runs for a long time.
- In LicenseMetric.ts, the licenseKey variable is typed as any, which can lead to runtime errors if the structure of the response changes.

**Comment by Ca3de** [comment]
<img width="1512" alt="Screenshot 2024-10-16 at 3 42 50 PM" src="https://github.com/user-attachments/assets/b04a8a2b-b675-45ad-a98b-c47870f3ca0f">
<img width="1512" alt="Screenshot 2024-10-16 at 3 42 46 PM" src="https://github.com/user-attachments/assets/4434e91c-c793-47f1-aa4a-bb80be24b499">
<img width="1512" alt="Screenshot 2024-10-16 at 3 42 40 PM 1" src="https://github.com/user-attachments/assets/49bc8e92-7d3c-4127-908c-5b27955c9783">
<img width="1512" alt="Screenshot 2024-10-16 at 3 42 40 PM" src="https://github.com/user-attachments/assets/cb920a9d-111e-4a28-ab8a-1dc1e385b29c">
<img width="1512" alt="Screenshot 2024-10-16 at 3 42 33 PM" src="https://github.com/user-attachments/assets/b587c442-4357-4f06-9794-3d1be884bde1">


 List of 5-10 Bugs in the Repository
Here are some bugs and potential issues based on reviewing the code:

Errors(These are most likely because I tried running the program on Mac):
1. **Cross-Platform Incompatibility**:
   - The project is specifically designed to work in **Windows Command Prompt**, making it incompatible with PowerShell, Linux, or macOS environments. This limits the usability of the project and could be addressed by writing platform-agnostic scripts or using tools like `cross-env`.

2. **Cannot Find Compiled JavaScript Modules (`MODULE_NOT_FOUND`)**:
   - The project frequently encounters `Cannot find module` errors after running `npm run build`. This indicates that TypeScript files are not compiling correctly into JavaScript or that the output directory is incorrect. Double-check `tsconfig.json` to ensure that the output files are generated in the correct location.

3. **Missing Environment Variables (GitHub Token)**:
   - Several tests require a `GITHUB_TOKEN` to run. Without this token, the tests crash, calling `process.exit(1)`. The tests should handle this case more gracefully by alerting the user to the missing token, rather than exiting abruptly.

4. **Outdated Dependencies**:
   - Some dependencies like `inflight` and `glob` are deprecated. This introduces the risk of security vulnerabilities and memory leaks. These libraries should be updated or replaced with more modern alternatives.

5. **Jest Test Failures (`BusFactor.test.ts` and `RampUpMetric.test.ts`)**:
   - The Jest tests are failing with errors like `Expected: > 0, Received: 0`, indicating that the metric calculations (e.g., BusFactor) are returning unexpected results. This could be due to the tests relying on live API data from GitHub, which may be incomplete or incorrect during testing.

6. **Hardcoded GitHub API Data**:
   - The tests rely on real-time GitHub API data, which can be unreliable due to API limits or data inconsistencies. This can cause test failures. Consider mocking API responses to ensure consistent test results.

7. **Inconsistent Script Names in `package.json`**:
   - The `package.json` scripts have some inconsistencies in their naming conventions (e.g., `start-CorrectnessMetric` vs `start-CorrectnessMetrics`). This can cause confusion when running scripts and should be standardized.

8. **Missing Error Handling**:
   - Some functions exit the process abruptly when encountering an error (e.g., missing GitHub token). Adding more robust error handling with meaningful messages could improve the user experience.

9. **Improper Logging Configuration**:
   - The logging configuration in `Logger.ts` could be enhanced with better separation of log levels (info, error, debug) to allow for easier debugging during development.

10. **File Permissions for `run` Script**:
   - On non-Windows systems, the `run` script lacks the proper executable permissions. Running `chmod +x ./run` resolves this, but this could be avoided by using cross-platform solutions for script execution.
